export { default as GitHub } from './github.png'
export { default as LinkedIn } from './linkedin.png'
export { default as Cinema } from './projects/cinema.jpg'
export { default as ExpandMore } from './expandMore.svg'
export { default as Mail } from './mail.svg'
export { default as Me } from './me.jpg'
export { default as OpenInNew } from './openInNew.svg'
export { default as PolishFlag } from './polishFlag.svg'
export { default as UKFlag } from './UKFlag.svg'
export { default as Menu } from './menu.svg'
export { default as Close} from './close.svg'